apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app.kubernetes.io/name: search
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.containers.search.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: search
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/settings/frontend-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: search
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: search
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
        readinessProbe:
          httpGet:
            path: "/"
            port: 80
        image: {{ printf "%s/%s:%s" $.Values.global.image.registry $.Values.containers.search.repository $.Values.containers.search.tag }}
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: trieve-frontend-config
