apiVersion: apps/v1
kind: Deployment
metadata:
  name: trieve-embedding
spec:
  replicas: 1
  selector: {}
  template:
    spec:
      containers:
        - name: embedding
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
          image: ghcr.io/huggingface/text-embeddings-inference
          ports:
            - containerPort: 80

