apiVersion: apps/v1
kind: Deployment
metadata:
  name: trieve-embedding
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: embedding
          args:
            - --model-id
            - naver/efficient-splade-VI-BT-large-query
            - --revision
            - main
            - --pooling
            - splade
          resources:
            requests:
              memory: 500Mi
            limits:
              memory: 500Mi
