apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app.kubernetes.io/name: chat
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chat
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chat
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: chat
        image: {{ (printf "%s%s:%s" (ternary "trieve/" "localhost:5000/" (eq .Values.environment "aws")) "chat" .Values.containers.chat.tag) }}
        ports:
          - containerPort: 80
        env:
          - name: VITE_API_HOST
            value: {{ .Values.config.vite.apiHost }}
          - name: VITE_SEARCH_UI_URL
            value: {{ .Values.config.vite.searchUiUrl }}
          - name: VITE_DASHBOARD_URL
            value: {{ $.Values.config.vite.dashboardUrl }}
