apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-collapse
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  suspend: {{ $.Values.config.trieve.disableCrons }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clustering
              image: {{ printf "%s:%s" "trieve/clickhouse-collapse-query-script" .Values.containers.clickhouse_collapse.tag }}
              imagePullPolicy: IfNotPresent
              env:
                - name: CLICKHOUSE_DSN
                  value: {{ .Values.clickhouse.dsn }}
          restartPolicy: Never
