apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-worker
  labels:
    app.kubernetes.io/name: file-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: file-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: file-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if eq $.Values.environment "gcloud" }}
      serviceAccountName: cloud-postgres-service-account
      {{- end }}
      containers:
      - name: file-worker
        image: {{ printf "%s%s:%s" (ternary "trieve/" "localhost:5001/" (ne .Values.environment "local")) "file_worker" .Values.containers.file_worker.tag }}
        env:
          - name: ADMIN_API_KEY
            value: {{ .Values.config.trieve.adminApiKey }}
          - name: BASE_SERVER_URL
            value: {{ .Values.config.trieve.baseServerUrl }}
          - name: REDIS_URL
            value: {{ ( ternary "redis://:redis@trieve-redis-master.default.svc.cluster.local:6379" .Values.config.redis.uri (eq .Values.config.redis.useSubchart true)) }}
          - name: QDRANT_URL
            value: {{ ( ternary "http://trieve-qdrant.default.svc.cluster.local:6334" .Values.config.qdrant.qdrantUrl (eq .Values.config.qdrant.useSubchart true)) }}
          - name: QDRANT_API_KEY
            value: {{ .Values.config.qdrant.apiKey }}
          - name: QUANTIZE_VECTORS
            value: {{ .Values.config.qdrant.quantizeVectors | quote }}
          - name: REPLICATION_FACTOR
            value: {{ .Values.config.qdrant.replicationFactor | quote }}
          - name: DATABASE_URL
            value: {{ ( ternary "postgres://postgres:password@trieve-postgresql.default.svc.cluster.local:5432/trieve" .Values.postgres.dbURI (eq .Values.postgres.useSubchart true)) }}
          - name: SMTP_RELAY
            value: {{ .Values.config.smtp.relay }}
          - name: SMTP_USERNAME
            value: {{ .Values.config.smtp.username }}
          - name: SMTP_PASSWORD
            value: {{ .Values.config.smtp.password }}
          - name: SMTP_EMAIL_ADDRESS
            value: {{ .Values.config.smtp.emailAddress }}
          - name: OPENAI_API_KEY
            value: {{ .Values.config.openai.apiKey }}
          - name: LLM_API_KEY
            value: {{ .Values.config.llm.apiKey }}
          - name: SECRET_KEY
            value: {{ .Values.config.trieve.secretKey | quote }}
          - name: SALT
            value: {{ .Values.config.trieve.salt }}
          - name: S3_ENDPOINT
            value: {{ .Values.config.s3.endpoint }}
          - name: S3_ACCESS_KEY
            value: {{ .Values.config.s3.accessKey }}
          - name: S3_SECRET_KEY
            value: {{ .Values.config.s3.secretKey }}
          - name: S3_BUCKET
            value: {{ .Values.config.s3.bucket }}
          - name: COOKIE_SECURE
            value: {{ .Values.config.trieve.cookieSecure | quote }}
          - name: QDRANT_COLLECTION
            value: {{ .Values.config.qdrant.collection }}
          - name: TIKA_URL
            value: http://tika.default.svc.cluster.local:9998
          - name: OPENAI_BASE_URL
            value: {{ .Values.config.openai.baseUrl }}
          - name: STRIPE_SECRET
            value: {{ .Values.config.stripe.secret }}
          - name: STRIPE_WEBHOOK_SECRET
            value: {{ .Values.config.stripe.webhookSecret }}
          - name: ADMIN_DASHBOARD_URL
            value: {{ .Values.config.trieve.adminDashboardUrl }}
          - name: OIDC_CLIENT_SECRET
            value: {{ .Values.config.oidc.clientSecret }}
          - name: OIDC_CLIENT_ID
            value: {{ .Values.config.oidc.clientId }}
          - name: OIDC_AUTH_REDIRECT_URL
            value: {{ .Values.config.oidc.authRedirectUrl }}
          - name: OIDC_ISSUER_URL
            value: {{ .Values.config.oidc.issuerUrl }}
          - name: GPU_SERVER_ORIGIN
            value: {{ .Values.config.trieve.gpuServerOrigin }}
          - name: SPARSE_SERVER_QUERY_ORIGIN
            value: {{ .Values.config.trieve.sparseServerQueryOrigin }}
          - name: SPARSE_SERVER_DOC_ORIGIN
            value: {{ .Values.config.trieve.sparseServerDocOrigin }}
          - name: SPARSE_SERVER_ORIGIN
            value: {{ .Values.config.trieve.sparseServerOrigin }}
          - name: EMBEDDING_SERVER_ORIGIN
            value: {{ .Values.config.trieve.embeddingServerOrigin }}
          - name: EMBEDDING_SERVER_ORIGIN_BGEM3
            value: {{ .Values.config.trieve.embeddingServerOriginBGEM3 }}
          - name: RERANKER_SERVER_ORIGIN
            value: {{ .Values.config.trieve.rerankerServerOrigin }}
          - name: UNLIMITED
            value: {{ .Values.config.trieve.unlimited | quote }}
          - name: REDIS_CONNECTIONS
            value: {{ .Values.config.redis.connections | quote }}
          - name: AWS_REGION
            value: {{ .Values.config.s3.region }}
          - name: CLICKHOUSE_URL
            value: {{ .Values.config.analytics.clickhouseUrl | quote }}
          - name: CLICKHOUSE_DB
            value: {{ .Values.config.analytics.clickhouseDB | quote }}
          - name: CLICKHOUSE_USER
            value: {{ .Values.config.analytics.clickhouseUser | quote }}
          - name: CLICKHOUSE_PASSWORD
            value: {{ .Values.config.analytics.clickhousePassword | quote }}
          - name: USE_ANALYTICS
            value: {{ .Values.config.analytics.enabled | quote }}
      {{- if eq $.Values.environment "gcloud" }}
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL Auth Proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--structured-logs"
          - "--auto-iam-authn"
          # Replace DB_PORT with the port the proxy should listen on
          - "--port=5432"
          - "studious-lore-405302:us-west1:trieve-cloud"
        securityContext:
          # The default Cloud SQL Auth Proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        # You should use resource requests/limits as a best practice to prevent
        # pods from consuming too many resources and affecting the execution of
        # other pods. You should adjust the following values based on what your
        # application needs. For details, see
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          requests:
            # The proxy's memory use scales linearly with the number of active
            # connections. Fewer open connections will use less memory. Adjust
            # this value based on your application's requirements.
            memory: "2Gi"
            # The proxy's CPU use scales linearly with the amount of IO between
            # the database and the application. Adjust this value based on your
            # application's requirements.
            cpu:    "1"
      {{- end }}
