apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-worker
  labels:
    app.kubernetes.io/name: file-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.containers.file_worker.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: file-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: file-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: file-worker
        resources:
          {{- toYaml .Values.containers.server.resources | nindent 12 }}
        image: {{ printf "%s:%s" "trieve/file_worker" .Values.containers.file_worker.tag }}
        envFrom:
          - configMapRef:
              name: trieve-server-config
