apiVersion: v1
kind: ConfigMap
metadata:
  name: trieve-frontend-config
data:
  VITE_API_HOST: {{ $.Values.config.vite.apiHost }}
  VITE_SEARCH_UI_URL: {{ $.Values.config.vite.searchUiUrl }}
  VITE_DASHBOARD_URL: {{ $.Values.config.vite.dashboardUrl }}
  VITE_BM25_ACTIVE: {{ .Values.config.trieve.bm25Active | quote }}
