apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: tcp-services
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: trieve
    meta.helm.sh/release-namespace: default
data:
  6379: "ingress-nginx/trieve-redis-master:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-redis
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-redis
spec:
  type: LoadBalancer
  ports:
    - name: proxied-tcp-6379
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-redis
{{- if (eq .Values.environment "local") }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dashboard
spec:
  ingressClassName: nginx
  rules:
    - host: dashboard.trieve.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashbord-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-chat
spec:
  ingressClassName: nginx
  rules:
    - host: chat.trieve.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-service
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-server
spec:
  ingressClassName: nginx
  rules:
    - host: api.trieve.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 8090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-search
spec:
  ingressClassName: nginx
  rules:
    - host: search.trieve.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-keycloak
spec:
  ingressClassName: nginx
  rules:
    - host: oidc.trieve.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-s3
spec:
  ingressClassName: nginx
  rules:
    - host: data.trieve.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-service
                port: 
                  number: 9000
{{- end }}
{{- if (eq .Values.environment "aws") }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dashboard
  namespace: ingress-nginx
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: "dashboard.trieve-aws.ai"
spec:
  ingressClassName: alb
  rules:
    - host: "dashboard.trieve.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-chat
  namespace: ingress-nginx
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: "chat.trieve-aws.ai"
spec:
  ingressClassName: alb
  rules:
    - host: "chat.trieve.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-service
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-server
  namespace: ingress-nginx
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: "api.trieve-aws.ai"
spec:
  ingressClassName: alb
  rules:
    - host: "api.trieve.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 8090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-search
  namespace: ingress-nginx
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: "search.trieve-aws.ai"
spec:
  ingressClassName: alb
  rules:
    - host: "search.trieve.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-keycloak
  namespace: ingress-nginx
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: "oidc.trieve-aws.ai"
spec:
  ingressClassName: alb
  rules:
    - host: "oidc.trieve.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-s3
  namespace: ingress-nginx
  labels:
    app: trieve
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: "data.trieve-aws.ai"
spec:
  ingressClassName: alb
  rules:
    - host: "data.trieve.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-service
                port:
                  number: 9000
{{- end }}
