apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: keycloak
        image: {{ printf "%s%s:%s" (ternary (printf "%s.dkr.ecr.%s.amazonaws.com/" .Values.accountId .Values.region) "localhost:5000/" (eq .Values.environment "aws")) "keycloak" .Values.containers.keycloak.tag }}
        ports:
          - containerPort: 9000
          - containerPort: 42625
        volumeMounts:
          - name: keycloak-data
            mountPath: /opt/keycloak/data
        env:
          - name: KEYCLOAK_ADMIN
            value: {{ default "admin" .Values.config.keycloak.admin }}
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: {{ default "aintsecure" .Values.config.keycloak.adminPassword }}
          - name: KC_DB
            value: postgres
          - name: KC_DB_URL
            value: jdbc:postgresql://trieve-postgres.default.svc.cluster.local:5432/keycloak
          - name: KC_DB_USERNAME
            value: {{ default "postgres" .Values.config.keycloak.dbUsername }}
          - name: KC_DB_PASSWORD
            value: {{ default "password" .Values.config.keycloak.dbPassword }}
          - name: KC_HEALTH_ENABLED
            value: true
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
