apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
  labels:
    app.kubernetes.io/name: mc
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mc
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mc
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: mc
          image: busybox:1.28
          command: ["sh", "-c", "echo MINIO INITSCRIPT . . .; sleep 4294967296"] 
      initContainers:
        - name: init-mc
          image: {{ printf "%s%s:%s" (ternary "minio/" "localhost:5000/" (ne .Values.environment "local")) "mc" .Values.containers.mc.tag }}
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.config.minio.rootUser }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.config.minio.rootPassword }}
            - name: S3_ACCESS_KEY
              value: {{ .Values.config.s3.accessKey }}
            - name: S3_SECRET_KEY
              value: {{ .Values.config.s3.secretKey }}
            - name: S3_BUCKET
              value: {{ .Values.config.s3.bucket }}
            - name: S3_URI
              value: "http://s3.default.svc.cluster.local:9000"
