apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: server-pdb
spec:
  minAvailable: "25%"
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.containers.search.replicas | default 3 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: server
        {{- if .Values.config.trieve.useSubtrace }}
        securityContext:
          capabilities:
            add: ["SYS_PTRACE"]
        command: 
          - "./subtrace-linux-amd64"
          - "run"
          - "--config /app/subtrace.yml"
          - "-tls=false"
          - "--"
          - "/app/trieve-server"
        {{- end }}
        image: {{ printf "%s:%s" "trieve/server" .Values.containers.server.tag }}
        resources:
          {{- toYaml .Values.containers.server.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: "/api/health"
            port: 8090
        readinessProbe:
          httpGet:
            path: "/api/health"
            port: 8090
        ports:
          - containerPort: 8090
        envFrom:
          - configMapRef:
              name: trieve-server-config
