apiVersion: packages.glasskube.dev/v1alpha1
kind: Package
metadata:
  name: hackernews
  namespace: trieve
spec:
  packageInfo:
    name: trieve-gcp
    repositoryName: trieve
    version: v0.11.8+3
  values:
    cpuMode:
      value: 'false'
    domain:
      value: trieve-hackernews.glasskube.com
    keyForAnthropicApi:
      value: ' '
    keyForJinaCodeApi:
      value: ' '
    keyForLlmApi:
      value: ' '
    keyForOpenaiApi:
      value: ' '
    s3AccessKey:
      value: ''
    s3AwsRegion:
      value: ''
    s3BucketName:
      value: ''
    s3Endpoint:
      value: ''
    s3SecretKey:
      value: ''
    smtpEmailAddress:
      value: ' '
    smtpServerUrl:
      value: ' '
    smtpUsername:
      value: ' '
    smtpUsernamePassword:
      value: ' '