{{- include "trieve.worker.deployment" (dict 
  "name" "crawl-worker"
  "replicas" ($.Values.containers.crawl_worker.replicas | default 1)
  "image" (dict 
    "repository" $.Values.containers.crawl_worker.repository
    "tag" $.Values.containers.crawl_worker.tag
  )
  "resources" $.Values.containers.crawl_worker.resources
  "Values" $.Values
  "Release" $.Release
  "Template" $.Template
)
-}}
