{{- include "trieve.worker.deployment" (dict 
  "name" "update-worker"
  "replicas" ($.Values.containers.update_worker.replicas | default 1)
  "image" (dict 
    "repository" $.Values.containers.update_worker.repository
    "tag" $.Values.containers.update_worker.tag
  )
  "resources" $.Values.containers.update_worker.resources
  "Values" $.Values
  "Release" $.Release
  "Template" $.Template
)
-}}
