{{- range $index, $service := $.Values.clone }}
{{- if ne $index 0 }}
---
{{- end }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clone-qdrant-{{ $service.clone_name }}
  labels:
    app.kubernetes.io/name: clone-qdrant-{{ $service.clone_name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  suspend: true
  schedule: "0 0 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/settings/backend-configmap.yaml") . | sha256sum }}
        spec:
          restartPolicy: Never
          {{- if $.Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
          {{- end }}
          containers:
          - name: clone-qdrant-{{ $service.clone_name }}
            image: {{ printf "%s%s:%s" $.Values.global.image.registry $.Values.containers.clone_qdrant.repository $.Values.containers.clone_qdrant.tag }}
            envFrom:
              - configMapRef:
                  name: trieve-server-config
            env:
              - name: ORIGIN_QDRANT_URL
                value: {{ $service.origin }}
              - name: NEW_QDRANT_URL
                value: {{ $service.dest }}
              - name: COLLECTION_TO_CLONE
                value: {{ $service.collection }}
              - name: TIMEOUT_MS
                value: {{ $service.timeout_ms | quote }}
              - name: QDRANT_TIMEOUT_SEC
                value: {{ $service.qdrant_timeout_sec | quote  }}
              - name: OFFSET_ID
                value: {{ $service.offset_id | quote }}
{{- end }}
