apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trieve
  annotations:
    networking.gke.io/managed-certificates: trieve-cert
spec:
  rules:
    - host: auth.localtrieve.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trieve-keycloak-service
                port:
                  number: 8080
    - host: api.localtrieve.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trieve-server
                port:
                  name: server
    - host: analytics.localtrieve.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trieve-ui-analytics
                port:
                  name: http
    - host: chat.localtrieve.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trieve-ui-chat
                port:
                  name: http
    - host: dashboard.localtrieve.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trieve-ui-dashboard
                port:
                  name: http
    - host: search.localtrieve.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trieve-ui-search
                port:
                  name: http
