apiVersion: v2
name: trieve
description: Helm chart expressing Trieve deployment and dependencies
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.9.0
    condition: redis.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.2.5
    condition: postgres.useSubchart
  - name: qdrant
    repository: https://qdrant.github.io/qdrant-helm
    version: 0.8.4
    condition: config.qdrant.useSubchart
